language: php
php:
  - 7.2
  - 7.3
env:
  matrix:
    - COMPOSER_FLAGS=""
before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - composer ocular-code-coverage-upload
